config/routes.rb
Rails.application.routes.draw do


  scope :admin do
    get "dashboard" => "dashboard#index"
    devise_for :users, :skip => [:registrations]
    resources :users
    resources :saledetails
      resources :sales
    resources :imports
    resources :products
    resources :categories
    resources :suppliers
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord


  #Associations
  has_many :products

  #Validation
  validates :category_name,presence:true
end

app/models/import.rb
class Import < ApplicationRecord
  #Associations
  belongs_to :suppiler, optional: true
  belongs_to :user, optional: true
  has_many :products, inverse_of: :import
  accepts_nested_attributes_for :products, :reject_if => :all_blank, :allow_destroy => true
end

app/models/product.rb
class Product < ApplicationRecord


  #Associations
  belongs_to :category,optional: true
  belongs_to :import

  #Validation
  # validates :product_name
  # validates :product_qty
  # validates :unit_price_instock,numericality: {grater_then_or_equal_to: 0}
  # validates :sale_unit_price,numericality: {grater_then_or_to: 0}

end

app/models/sale.rb
class Sale < ApplicationRecord



end

app/models/saledetail.rb
class Saledetail < ApplicationRecord

  #Associations

end

app/models/supplier.rb
class Supplier < ApplicationRecord

  #Associations
  has_many :import
  belongs_to :user,optional: true

  #Validation
  validates :supplier_name, presence: true
  validates :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # Association
  has_many :suppliers
  has_many :imports
  #Devise
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable



  #Validation
  # has_attached_file :image, style: { medium: "300x500>",thumb: "100x100>" }
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  #instance method
  def set_default_role
    self.role ||= :user
  end

  # def full_name
  #   "#{first_name}" "#{last_name}"
  # end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def view_link_icon(object)
    if current_user.try(:admin?)
      link_to "#{content_tag(:i,"",class:"glyphicon glyphicon-eye-open")}".html_safe, object ,class:"btn btn-info btn-simple btn-xs" ,rel:"tooltip", title:"View"
    end
  end
  def edit_link_icon(object)
    if current_user.try(:admin?)
      controller = "kkkkkk"
      if (controller_name == "suppliers/suppliers")
        controller = "suppliers/"
      end
      link_to "#{content_tag(:i,"",class:"glyphicon glyphicon-pencil")}".html_safe, "#{controller_name}/#{object.id}/edit" ,class:"btn btn-info btn-simple btn-xs" ,rel:"tooltip", title:"Edit"
    end
  end

  def edit_link_in_show(object)
    if current_user.try(:admin?)
      link_to "#{content_tag(:i,"",class:"glyphicon glyphicon-pencil")}".html_safe, "#{object.id}/edit" ,class:"btn btn-info btn-simple btn-xs" ,rel:"tooltip", title:"Edit"
    end
  end

  def delete_link_icon(object)
    if current_user.try(:admin?)
      link_to "#{content_tag(:i,"",class:"glyphicon glyphicon-trash")}".html_safe, object, method: :delete,data: {confirm: "Are you sure?"} ,class:"btn btn-info btn-simple btn-xs" ,rel:"tooltip", title:"Delete"
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/saledetails_helper.rb
module SaledetailsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
  
end

app/helpers/suppliers_helper0.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name(user)
    "#{user.first_name}" "#{user.last_name}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stockmanagement</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: #edeff0;">
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/shared/_clockandweather.html.erb
      <div class="row" style="margin-top:40px;">
        <div class="col-md-8">
      		<section class="panel panel-default">
      			<div class="panel-body weather-row">
      				<img src="/weather_image.jpg" height="243" alt="">
      					<div class="weather-head">
      						weather forecast
      					</div>
      							<div class="form-group country-select">
      								<select class="width100p" data-placeholder="New York">
      									<option value="">New York</option>
      									<option value="">London</option>
      									<option value="">Australia</option>
      									<option value="">Canada</option>
      									<option value="">China</option>
      									<option value="">New York</option>
      								</select>
      							</div>
      						</div>

      				<div class="panel-footer">
      					<div class="row weather-full-info">
      						<div class="col-md-3 today-status">
      							<h1>Today</h1>
      							<span class="wi wi-day-cloudy"></span>
      							<div class="degree">37</div>
      						</div>
      						<div class="col-md-9">
      							<ul>
      								<li>
      									<h2>Tomorrow</h2>
      									<span class="wi wi-day-cloudy text-primary"></span>
      									<div class="statistics">32</div>
      								</li>
      								<li>
      									<h2>Mon</h2>
      									<span class="wi wi-day-cloudy text-danger"></span>
      									<div class="statistics">40</div>
      								</li>
      								<li>
      									<h2>Tue</h2>
      									<span class="wi wi-day-cloudy text-info"></span>
      									<div class="statistics">25</div>
      								</li>
      								<li>
      									<h2>Wed</h2>
      									<span class="wi wi-day-cloudy text-success"></span>
      									<div class="statistics">37</div>
      								</li>
      								<li>
      									<h2>Thu</h2>
      									<span class="wi wi-day-cloudy text-warning"></span>
      									<div class="statistics">15</div>
      								</li>
      								<li>
      									<h2>Fri</h2>
      									<span class="wi wi-day-cloudy"></span>
      									<div class="statistics">21</div>
      								</li>
      							</ul>
      						</div>
      					</div>
      				</div>
      			</section>
      		</div>

      		<div class="col-md-4">
      			<section class="panel panel-default">
      				<div class="clock-panel">
      					<h1>DECEMBER 16</h1>
      					<p class="text-left">2016, Friday</p>
      					<p class="text-left">7:53 PM</p>
      				</div>

      				<ul id="clock">
      					<li id="sec"></li>
      					<li id="hour"></li>
      					<li id="min"></li>
      				</ul>

      				<ul class="clock-category">
      					<li>
      						<a href="#" class="active">
      							<i class="fa fa-clock-o"></i>
      							<span>Clock</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Alarm</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Stop watch</span>
      						</a>
      					</li>
      					<li>
      						<a href="#">
      							<i class="fa fa-clock-o"></i>
      							<span>Timer</span>
      						</a>
      					</li>
      				</ul>
      			</section>
      		</div>
      	</div>
        <div class="row">
          <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-body padding15">
                  <h5 class="md-title mt0 mb10">Site Statistics</h5>
                  <div id="basicFlotLegend" class="flotLegend"></div>
                  <div id="basicflot" class="flotChart"></div>
                </div><!-- panel-body -->

                <div class="panel-footer">
                  <div class="tinystat pull-left">
                    <div id="sparkline" class="chart mt5"></div>
                      <div class="datainfo">
                        <span class="text-muted">Average</span>
                        <h4>$9,201</h4>
                      </div>
                  </div><!-- tinystat -->

                  <div class="tinystat pull-right">
                    <div id="sparkline2" class="chart mt5"></div>
                      <div class="datainfo">
                        <span class="text-muted">Total</span>
                        <h4>$8,201</h4>
                      </div>
                  </div><!-- tinystat -->
                </div><!-- panel-footer -->
            </div><!-- panel -->
          </div>

          <div class="col-md-4">
              <div class="panel panel-default">
                  <div class="panel-body padding15">
                      <h5 class="md-title mt0 mb10">Site Visitors</h5>
                      <div id="basicFlotLegend2" class="flotLegend"></div>
                      <div id="basicflot2" class="flotChart"></div>
                  </div><!-- panel-body -->
                  <div class="panel-footer">
                      <div class="tinystat pull-left">
                          <div id="sparkline3" class="chart mt5"></div>
                          <div class="datainfo">
                              <span class="text-muted">Average</span>
                              <h4>52,201</h4>
                          </div>
                      </div><!-- tinystat -->
                      <div class="tinystat pull-right">
                          <div id="sparkline4" class="chart mt5"></div>
                          <div class="datainfo">
                              <span class="text-muted">Total</span>
                              <h4>11,201</h4>
                          </div>
                      </div><!-- tinystat -->
                  </div><!-- panel-footer -->
              </div><!-- panel -->
          </div>

          <div class="col-md-4">
              <div class="panel panel-default">
                  <div class="panel-body padding15">
                      <h5 class="md-title mt0 mb10">Site Impressions</h5>
                      <div id="basicFlotLegend3" class="flotLegend"></div>
                      <div id="basicflot3" class="flotChart"></div>
                  </div><!-- panel-body -->
                  <div class="panel-footer">
                      <div class="tinystat pull-left">
                          <div id="sparkline5" class="chart mt5"></div>
                          <div class="datainfo">
                              <span class="text-muted">Average</span>
                              <h4>37,101</h4>
                          </div>
                      </div><!-- tinystat -->
                      <div class="tinystat pull-right">
                          <div id="sparkline6" class="chart mt5"></div>
                          <div class="datainfo">
                              <span class="text-muted">Total</span>
                              <h4>18,899</h4>
                          </div>
                      </div><!-- tinystat -->
                  </div><!-- panel-footer -->
              </div><!-- panel -->
          </div>
        </div><!-- row -->

app/views/shared/_footer.html.erb
<footer><!-- footer -->
  <p class="col-xs-12 footer-copyright">
    Powered by <b>Chhouk Tit Panhara</b>
  </p>
</footer>

app/views/shared/_left-panel.html.erb
<div class="leftpanel">
  <div class="media profile-left">
    <%if user_signed_in?%>
      <%=link_to users_path,:class=>"pull-left profile-thumb" do%>
      <%if current_user.image.blank?%>
        <img class="img-circle" src="/profile.png" alt="">
      <%else%>
        <img class="img-circle" src="<%=current_user.image%>" alt="">
      <%end%>
    <%end%>

    <div class="media-body">

      <h4 class="media-heading"><%=current_user.username%></h4>
        <span class="user-options">
          <%=link_to users_path do%>
            <i class="glyphicon glyphicon-user"></i>
          <%end%>

          <%=link_to destroy_user_session_path do%>
            <i class="glyphicon glyphicon-log-out"></i>
          <%end%>

        </span>
    </div>
    <%end%>

  </div><!-- media -->


  <ul class="nav nav-pills nav-stacked">
    <li class="active">
      <%= link_to dashboard_path do  %>
        <i class="fa fa-home"></i> <span>Dashboard</span>
      <% end %>
  </li>

    <li class="parent"><a href="#"><i class="fa fa-edit"></i> <span>Products</span></a>

    </li>

    <li class="parent"><a href="#"><i class="fa fa-file-text"></i> <span>Supplier</span></a>
      <ul class="children">
        <%if current_user.try(:admin?)%>
          <li>
            <%=link_to "Add Supplier", new_supplier_path%>
          </li>
          <li>
            <%=link_to "Supplier List", suppliers_path%>
          </li>

        <%else%>
          <li>
            <%=link_to "Product List", suppliers_path%>
          </li>
        <%end%>

      </ul>
    </li>

    <li class="parent"><a href="#"><i class="fa fa-file-text"></i> <span>Import</span></a>
      <ul class="children">
        <%if current_user.try(:admin?)%>
          <li>
            <%=link_to "Add Import", new_import_path%>
          </li>
          <li>
            <%=link_to "Import List", imports_path%>
          </li>

        <%else%>
          <li>
            <%=link_to "Import List", imports_path%>
          </li>
        <%end%>

      </ul>
    </li>


    <li class="parent"><a href="#"><i class="fa fa-file-text"></i> <span>Customer</span></a>

    </li>
  </ul>
</div><!-- leftpanel -->

app/views/shared/_navbar.html.erb
<header>
  <div class="headerwrapper">
    <div class="header-left">
      <a href="/admin/dashboard" class="logo">
        <h4 class="admin-logo"><img src="" alt=""> Web Application </h4>

      </a>

      <div class="pull-right">
        <a href="#" class="menu-collapse">
          <i class="fa fa-bars"></i>
        </a>
      </div>
    </div><!-- header-left -->

    <div class="header-right">
      <div class="pull-right">
        <!-- <form class="form form-search" action="http://www.ravijaiswal.com/Moldavite/search-results.html">
          <input type="search" class="form-control" placeholder="Search" />
        </form> -->

        <div class="btn-group btn-group-option">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <%if user_signed_in?%>
              <%if current_user.image.blank?%>
                  <img class="img-circle avatar-img" alt="" src="/profile.png">
                <%else%>
                  <img class="img-circle avatar-img" alt="" src="<%=current_user.image%>">
              <%end%>
              <%else%>
            <%end%>
        		<span class="user-name"><%=current_user.username%></span>
        		<i class="fa fa-caret-down"></i>
          </button>
          <ul class="dropdown-menu pull-right" role="menu">
            <% if user_signed_in? %>
              <% if current_user.try(:admin?) %>
                <li>
                  <%= link_to current_user do %>
                    <i class="glyphicon glyphicon-user"></i>
                    My Profile
                  <%end%>
                  </li>
              <% end %>
            <% end %>

              <% if user_signed_in? %>
                <li>

                </li>

                <li>
                  <%= link_to destroy_user_session_path, :method => 'delete' do %>
                    <i class="glyphicon glyphicon-log-out"></i>
                    Sign Out
                  <%end%>
                </li>
              <% else %>

              <% end %>
          </ul>
        </div><!-- btn-group -->
      </div><!-- pull-right -->
    </div><!-- header-right -->
  </div><!-- headerwrapper -->
</header>