config/routes.rb
Rails.application.routes.draw do


  scope :admin do
    get "dashboard" => "dashboard#index"
    devise_for :users, :skip => [:registrations]
    resources :users
    resources :saledetails
      resources :sales
    resources :imports
    resources :products
    resources :categories
    resources :suppliers
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "dashboard#index"
end

app/models/saledetail.rb
class Saledetail < ApplicationRecord

  #Associations

end

app/controllers/saledetails_controller.rb
class SaledetailsController < ApplicationController
  before_action :set_saledetail, only: [:show, :edit, :update, :destroy]

  # GET /saledetails
  # GET /saledetails.json
  def index
    @saledetails = Saledetail.all
  end

  # GET /saledetails/1
  # GET /saledetails/1.json
  def show
  end

  # GET /saledetails/new
  def new
    @saledetail = Saledetail.new
  end

  # GET /saledetails/1/edit
  def edit
  end

  # POST /saledetails
  # POST /saledetails.json
  def create
    @saledetail = Saledetail.new(saledetail_params)

    respond_to do |format|
      if @saledetail.save
        format.html { redirect_to @saledetail, notice: 'Saledetail was successfully created.' }
        format.json { render :show, status: :created, location: @saledetail }
      else
        format.html { render :new }
        format.json { render json: @saledetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saledetails/1
  # PATCH/PUT /saledetails/1.json
  def update
    respond_to do |format|
      if @saledetail.update(saledetail_params)
        format.html { redirect_to @saledetail, notice: 'Saledetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @saledetail }
      else
        format.html { render :edit }
        format.json { render json: @saledetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saledetails/1
  # DELETE /saledetails/1.json
  def destroy
    @saledetail.destroy
    respond_to do |format|
      format.html { redirect_to saledetails_url, notice: 'Saledetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saledetail
      @saledetail = Saledetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saledetail_params
      params.require(:saledetail).permit(:sale_qty, :unit_price, :total)
    end
end

app/helpers/saledetails_helper.rb
module SaledetailsHelper
end

app/views/saledetails/_form.html.erb
<%= form_with(model: saledetail, local: true) do |form| %>
  <% if saledetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(saledetail.errors.count, "error") %> prohibited this saledetail from being saved:</h2>

      <ul>
      <% saledetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sale_qty %>
    <%= form.number_field :sale_qty, id: :saledetail_sale_qty %>
  </div>

  <div class="field">
    <%= form.label :unit_price %>
    <%= form.text_field :unit_price, id: :saledetail_unit_price %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total, id: :saledetail_total %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/saledetails/edit.html.erb
<h1>Editing Saledetail</h1>

<%= render 'form', saledetail: @saledetail %>

<%= link_to 'Show', @saledetail %> |
<%= link_to 'Back', saledetails_path %>

app/views/saledetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Saledetails</h1>

<table>
  <thead>
    <tr>
      <th>Sale qty</th>
      <th>Unit price</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @saledetails.each do |saledetail| %>
      <tr>
        <td><%= saledetail.sale_qty %></td>
        <td><%= saledetail.unit_price %></td>
        <td><%= saledetail.total %></td>
        <td><%= link_to 'Show', saledetail %></td>
        <td><%= link_to 'Edit', edit_saledetail_path(saledetail) %></td>
        <td><%= link_to 'Destroy', saledetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Saledetail', new_saledetail_path %>

app/views/saledetails/new.html.erb
<h1>New Saledetail</h1>

<%= render 'form', saledetail: @saledetail %>

<%= link_to 'Back', saledetails_path %>

app/views/saledetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sale qty:</strong>
  <%= @saledetail.sale_qty %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @saledetail.unit_price %>
</p>

<p>
  <strong>Total:</strong>
  <%= @saledetail.total %>
</p>

<%= link_to 'Edit', edit_saledetail_path(@saledetail) %> |
<%= link_to 'Back', saledetails_path %>